name: Test

on: push

env:
  CACHE_NAME: cache-image

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Cache
        uses: actions/cache@v1
        with:
          path: ${{ GITHUB_WORKFLOW }}
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
