name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check diredtories
        run: |
          echo "**************************************************************************************************"
          echo "The GITHUB_WORKSPACE is:"
          echo "$GITHUB_WORKSPACE"
          echo "**************************************************************************************************"
          echo "Current working directory is:"
          echo "$PWD"
          ls
          echo "**************************************************************************************************"
          cd AddTwoNumbers
          echo "$PWD"
          ls
          echo "**************************************************************************************************"

      - name: Checkout submodule
        shell: bash
        run: |
          echo "**************************************************************************************************"
          echo "$PWD"
          git submodule init
          git submodule update
          echo "**************************************************************************************************"
          cd AddTwoNumbers
          echo "$PWD"
          ls
          echo "**************************************************************************************************"
