name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - name: Setup Git
        run: |
          curl -O https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.17.1.tar.gz
          tar xzf ./git-2.17.1.tar.gz
          cd git-2.17.1
          sudo apt install git-all
          make configure
          ./configure --prefix=/usr
          make all doc info
          sudo make install install-doc install-html install-info

      - name: Check Git version
        shell: bash
        run: |
          git --version

      - name: Checkout
        uses: actions/checkout@v2

      - name: Check diredtories
        run: |
          echo "**************************************************************************************************"
          echo "The GITHUB_WORKSPACE is:"
          echo "$GITHUB_WORKSPACE"
          echo "**************************************************************************************************"
          echo "Current working directory is:"
          echo "$PWD"
          ls
          echo "**************************************************************************************************"
          cd AddTwoNumbers
          echo "$PWD"
          ls
          echo "**************************************************************************************************"

      - name: Checkout submodule
        shell: bash
        run: |
          echo "**************************************************************************************************"
          echo "$PWD"
          git submodule init
          git submodule update
          echo "**************************************************************************************************"
          cd AddTwoNumbers
          echo "$PWD"
          ls
          echo "**************************************************************************************************"
