name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check diredtories
        run: |
          echo "**************************************************************"
          echo "The GITHUB_WORKSPACE is:"
          echo "$GITHUB_WORKSPACE"
          echo "**************************************************************"
          echo "Current working directory is:"
          echo "$PWD"
          echo "**************************************************************"
