name: Test my action

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hellow World
        uses: ./
        with:
          who-to-greet: RML
